version: '3'

services:
  postgres:
    image: postgres
    container_name: my-postgres-container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/home/ethhp/golang_tests/web/go-gin-crud/database

volumes:
  postgres_data: